version: "3"

services:
  app:
    build: .
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - volume_node_modules:/workspace/node_modules
    ports: 
        - 3000:3000
    environment:
      - GENERATE_SOURCEMAP=false

volumes:
    volume_node_modules: